### ISSUE TITLE
after update to 17.3 linux. TypeError systemprefereces.subscribe.

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#366]
```
Uncaught Exception:
TypeError:systemPreferences.subscribeNotification is not a function
  at App.<anonymous>(/tmp/.mount_webcatoAks4V/resources/app/build/electron.js:39:23)
  at App.emit(events.js:205:15)
```

**Comment by quanglam2807** [comment]
Thanks for reporting! This is a regression from #359.
